1:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
2:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
3:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
4:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
5:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
6:
  topRight:
      x: 0
      y: 0
      z: 0
  prize:
  prizeFormat:
  playerWatch:
      x: 0
      y: 0
      z: 0
7:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
8:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
9:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
10:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
11:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
12:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
13:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
14:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
15:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
16:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
17:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
18:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
19:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
20:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
21:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
22:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
23:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
24:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
25:
  topRight:
    x: 0
    y: 0
    z: 0
  prize:
  prizeFormat:
  playerWatch:
    x: 0
    y: 0
    z: 0
exit:
  x: 0
  y: 0
  z: 0
month: 12